version: "3.7"
services:
  external-search-provider:
    container_name: external-search-provider
    build:
      context: .
      dockerfile: docker/external-search-provider/Dockerfile
    restart: unless-stopped
    depends_on:
      - ganache-cli
    environment:
      - GANACHE_URL=http://ganache-cli:8545

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  ganache-cli:
    extends:
      file: external/decentralised-scd-registry/docker-compose.yml
      service: ganache-cli
    ports:
      - 8545:8545
volumes:
  ganache_data:
  elasticsearch-data:
    driver: local