version: "3.7"
services:
  # It is impossible to store scds with an localhost url when using this comopse file.
  # Use the external IP of the storage device.
  external-search-provider:
    container_name: external-search-provider
    build:
      context: .
      dockerfile: docker/external-search-provider/Dockerfile
    restart: unless-stopped
    environment:
      - ETHEREUM_NETWORK_URL=${ETHEREUM_NETWORK_URL:-http://ganache-cli:8545}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://elasticsearch:9200}
      - REGISTRY_ADDRESS=${REGISTRY_ADDRESS:-0x222E34DA1926A9041ed5A87f71580D4D27f84fD3}
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    networks:
      - decentralised-scd-registry_ethereum-network
      - host
      - default

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default

volumes:
  elasticsearch-data:
    driver: local

networks:
  default:
    driver: bridge
  decentralised-scd-registry_ethereum-network:
    external: true
  host:
    external: true
