spring:
  jpa:
    properties:
      hibernate:
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              host: ${elasticsearch.url}
              index_schema_management_strategy: drop-and-create
              required_index_status: yellow
  main:
    allow-bean-definition-overriding: true
elasticsearch:
  url: localhost:9200