name: Build
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Compile Solidity
        run: ./gradlew compileSolidity --no-daemon
      - name: Generate contract wrappers
        run: ./gradlew generateContractWrappers --no-daemon

      - name: Gradle check
        run: ./gradlew check --no-daemon

      - name: Gradle build
        run: ./gradlew build --no-daemon
      - name: Jib build
        run: ./gradlew jibDockerBuild --no-daemon
