name: Build
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile Solidity
        run: ./gradlew compileSolidity
      - name: Generate contract wrappers
        run: ./gradlew generateContractWrappers

      - name: Gradle check
        run: ./gradlew check
      - name: Gradle test
        run: ./gradlew test

      - name: Gradle build
        run: ./gradlew build
      - name: Jib build
        run: ./gradlew jibDockerBuild
